//Garry's Mod
list.Add( "OverrideMaterials", "models/dav0r/hoverball" )
list.Add( "OverrideMaterials", "models/balloon/balloon_hl2" )
list.Add( "OverrideMaterials", "models/balloon/balloon_milfman" )
list.Add( "OverrideMaterials", "models/balloon/balloon_nips" )
//HL2
list.Add( "OverrideMaterials", "models/props_c17/metalladder001" )
list.Add( "OverrideMaterials", "models/props_c17/metalladder002" )
list.Add( "OverrideMaterials", "models/props_c17/metalladder003" )
list.Add( "OverrideMaterials", "models/props_debris/metalwall001a" )
list.Add( "OverrideMaterials", "models/props_canal/metalwall005b" )
list.Add( "OverrideMaterials", "models/props_combine/metal_combinebridge001" )
list.Add( "OverrideMaterials", "models/props_c17/furnituremetal001a" )
list.Add( "OverrideMaterials", "models/props_interiors/metalfence007a" )
list.Add( "OverrideMaterials", "models/props_pipes/pipeset_metal" )
list.Add( "OverrideMaterials", "models/props_pipes/pipeset_metal02" )
list.Add( "OverrideMaterials", "models/props_wasteland/metal_tram001a" )
list.Add( "OverrideMaterials", "models/props_canal/metalcrate001d" )
list.Add( "OverrideMaterials", "models/props_wasteland/rockcliff02a" )
list.Add( "OverrideMaterials", "models/props_wasteland/rockcliff02b" )
list.Add( "OverrideMaterials", "models/props_wasteland/rockcliff02c" )
list.Add( "OverrideMaterials", "models/props_wasteland/rockcliff04a" )
list.Add( "OverrideMaterials", "models/props_wasteland/dirtwall001a" )
list.Add( "OverrideMaterials", "models/props_foliage/oak_tree01" )
list.Add( "OverrideMaterials", "models/props_combine/pipes01" )
list.Add( "OverrideMaterials", "models/props_c17/furniturefabric001a" )
list.Add( "OverrideMaterials", "models/props_c17/furniturefabric002a" )
list.Add( "OverrideMaterials", "models/props_debris/plasterwall021a" )
list.Add( "OverrideMaterials", "models/props_debris/plasterwall009d" )
list.Add( "OverrideMaterials", "models/props_debris/plasterwall034a" )
list.Add( "OverrideMaterials", "models/props_debris/plasterwall039c" )
list.Add( "OverrideMaterials", "models/props_debris/plasterwall040c" )
list.Add( "OverrideMaterials", "models/props_debris/concretefloor013a" )
list.Add( "OverrideMaterials", "models/props_wasteland/concretefloor010a" )
list.Add( "OverrideMaterials", "models/props_debris/concretewall019a" )
list.Add( "OverrideMaterials", "models/props_wasteland/concretewall064b" )
list.Add( "OverrideMaterials", "models/props_wasteland/concretewall066a" )
list.Add( "OverrideMaterials", "models/props_lab/warp_sheet" )
list.Add( "OverrideMaterials", "models/combine_scanner/scanner_eye" )
list.Add( "OverrideMaterials", "models/props_wasteland/lighthouse_stairs" )
list.Add( "OverrideMaterials", "models/props_canal/rock_riverbed01a" )
list.Add( "OverrideMaterials", "models/props_canal/canalmap_sheet" )
list.Add( "OverrideMaterials", "models/props_canal/coastmap_sheet" )
list.Add( "OverrideMaterials", "models/effects/slimebubble_sheet" )
list.Add( "OverrideMaterials", "models/props_lab/generatorconsole_disp" )
list.Add( "OverrideMaterials", "models/props_combine/combine_interface_disp" )
list.Add( "OverrideMaterials", "models/props_combine/health_charger_glass" )
list.Add( "OverrideMaterials", "models/props_lab/xencrystal_sheet" )
list.Add( "OverrideMaterials", "models/props_combine/prtl_sky_sheet" )
list.Add( "OverrideMaterials", "models/props_lab/Tank_Glass002" )
list.Add( "OverrideMaterials", "models/props_foliage/ivy01" )
list.Add( "OverrideMaterials", "models/props_junk/TrafficCone001a" )
list.Add( "OverrideMaterials", "models/Player/player_chrome1" )
list.Add( "OverrideMaterials", "models/Combine_Dropship/combine_fenceglow" )
list.Add( "OverrideMaterials", "models/props_combine/Combine_Citadel001" )
list.Add( "OverrideMaterials", "models/props_combine/combine_fenceglow" )
list.Add( "OverrideMaterials", "models/props_combine/combine_intmonitor001_disp" )
list.Add( "OverrideMaterials", "models/props_combine/combine_monitorbay_disp" )
list.Add( "OverrideMaterials", "models/props_combine/masterinterface_alert" )
list.Add( "OverrideMaterials", "models/manhack/Blur01" )
list.Add( "OverrideMaterials", "models/props_combine/masterinterface01c" )
list.Add( "OverrideMaterials", "models/props_combine/tpballglow" )
list.Add( "OverrideMaterials", "models/props_c17/fisheyelens" )
list.Add( "OverrideMaterials", "models/dog/eyeglass" )
list.Add( "OverrideMaterials", "models/props_lab/door_klab01" )
list.Add( "OverrideMaterials", "models/props_lab/eyescanner_disp" )
list.Add( "OverrideMaterials", "models/props_combine/metal_combinebridge001" )
//CSS
list.Add( "OverrideMaterials", "models//props/de_tides/clouds" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspa" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspb" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspc" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspd" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspf" )
list.Add( "OverrideMaterials", "models/props/cs_office/offinspg" )
list.Add( "OverrideMaterials", "models/Shadertest/predator" )
//OTHER
list.Add( "OverrideMaterials", "totster/comshieldwall" )
list.Add( "OverrideMaterials", "totster/tp_refract" )
list.Add( "OverrideMaterials", "totster/spawn_effect" )
list.Add( "OverrideMaterials", "totster/screenwarp" )
//EP2
list.Add( "OverrideMaterials", "effects/borealis_plans_01" )
list.Add( "OverrideMaterials", "effects/borealis_plans_02" )
list.Add( "OverrideMaterials", "effects/borealis_plans_03" )
list.Add( "OverrideMaterials", "models/Debug/debugmesh" )
list.Add( "OverrideMaterials", "models/props_forest/fence_chicken_alpha" )
//PORTAL

//TF2
list.Add( "OverrideMaterials", "models/props_2fort/roof_metal001" )
list.Add( "OverrideMaterials", "models/props_2fort/window_glass004" )
list.Add( "OverrideMaterials", "models/props_badlands/glass_silo" )

//Copyright Totsters Extra Stuff - Re-Release of this Addon will result in Castration.