					//Materials
resource.AddFile("materials/totster/comshieldwall.vmt")
resource.AddFile("materials/totster/comshieldwall.vtf")
resource.AddFile("materials/totster/screenwarp.vmt")
resource.AddFile("materials/totster/spawn_effect.vmt")
resource.AddFile("materials/totster/tp_refract.vmt")
resource.AddFile("materials/trails/bubble.vmt")
resource.AddFile("materials/trails/comshieldwall.vmt")
resource.AddFile("materials/trails/exit1.vmt")
resource.AddFile("materials/trails/screenwarp.vmt")
resource.AddFile("materials/trails/spawn_effect.vmt")
resource.AddFile("materials/trails/spawn_effect2.vmt")
resource.AddFile("materials/trails/tp_refract.vmt")

					//LUA
AddCSLuaFile("autorun/npc_control.lua")
AddCSLuaFile("autorun/tes_menu.lua")
AddCSLuaFile("autorun/totsters_extra_language.lua")
AddCSLuaFile("autorun/totsters_extra_npcs.lua")
AddCSLuaFile("autorun/totsters_extra_npc_weapons.lua")
AddCSLuaFile("autorun/totsters_extra_entities.lua")
AddCSLuaFile("autorun/client/extrabuttons.lua")
AddCSLuaFile("autorun/client/extramaterials.lua")
AddCSLuaFile("autorun/client/extraoverlays.lua")
AddCSLuaFile("autorun/client/extratrails.lua")
AddCSLuaFile("autorun/client/stereoscopymenu.lua")
AddCSLuaFile("autorun/client/extraropematerials.lua")
AddCSLuaFile("autorun/client/extralampropematerials.lua")
AddCSLuaFile("autorun/client/extraballoonmaterials.lua")
AddCSLuaFile("autorun/client/extrathrusters.lua")
AddCSLuaFile("autorun/client/extralamptextures.lua")
AddCSLuaFile("autorun/client/extrapaint.lua")
AddCSLuaFile("autorun/client/extrawheels.lua")
//AddCSLuaFile("gamemodes/sandbox/entities/entities/gmod_emitter/fx_extrastuff.lua")

//Copyright Totsters Extra Stuff - Re-Release of this Addon will result in Castration.