	if ( CLIENT ) then
	//World spawn deserved to be at the top because it is the thing that can happen quite a lot
	language.Add("worldspawn", "World")
	//Vehicles
	language.Add("prop_vehicle", "Vehicle")
	language.Add("prop_vehicle_airboat", "Airboat")
	language.Add("prop_vehicle_cannon", "Cannon")
	language.Add("prop_vehicle_crane", "Crane")
	language.Add("prop_vehicle_driveable", "Vehicle(Drivable)")
	language.Add("prop_vehicle_jeep", "Jeep")
	language.Add("prop_vehicle_prisoner_pod", "Pod")
	//Stool Stuff and MISC
	language.Add("gmod_thruster", "Thruster")
	language.Add("gmod_cameraprop", "Camera")
	language.Add("gmod_rtcameraprop", "RT Camera")
	language.Add("gmod_turret", "Turret")
	language.Add("gmod_lamp", "Lamp")
	language.Add("gmod_balloon", "Balloon")
	language.Add("gmod_button", "Button")
	language.Add("gmod_emitter", "Emitter")
	language.Add("gmod_nail", "Nail")
	language.Add("prop_ragdoll", "Ragdoll")
	language.Add("entityflame", "Fire")
	//SENTS
	language.Add("sent_ball", "Bouncy Ball")
	//Hammer Stuff
	language.Add("func_physbox", "Physbox")
	language.Add("tank", "Tank")
	language.Add("tracktrain", "Elevator")
	language.Add("env_laser", "Laser")
	language.Add("prop_physics_respawnable", "Prop Respawnable")
	language.Add("env_headcrabcanister", "Headcrab Cannister")
	language.Add("func_rotating", "Rotating Object")
	language.Add("env_fire", "Fire")
	language.Add("func_door", "Door")
	language.Add("func_door_rotating", "Rotating Door")
	language.Add("trigger_hurt", "Trigger(Hurt)")
	language.Add("env_explosion", "Explosion")
	language.Add("trigger_physics_trap", "Trap")
	language.Add("point_hurt", "Hurt Point")
	language.Add("point_tesla", "Tesla")
	language.Add("env_beam", "Beam")
	language.Add("prop_physics_override", "Prop(Override)")
	language.Add("trigger_waterydeath", "Leeches")
	language.Add("point_push", "Pushed to your death")
	language.Add("prop_thumper", "Thumper")
	language.Add("env_flare", "Flare")
	//NPCS
	language.Add("combine_mine", "Combine Mine")
	language.Add("npc_hunter", "Hunter")
	language.Add("npc_antlion_worker", "Acid Antlion Worker") 
	language.Add("npc_helicopter", "Helicopter")
	language.Add("npc_stalker", "Stalker")
	language.Add("npc_fastzombie_torso", "Fastzombie Torso")
	language.Add("npc_clawscanner", "Clawscanner")
	language.Add("npc_ichthyosaur", "Ichthyosaur")
	language.Add("npc_grenade_frag", "Frag Grenade")
	//Weapons
	language.Add("prop_combine_ball", "Combine Ball")
	language.Add("hunter_flechette", "Hunter Flechette")
	language.Add("HL2_Annabelle", "Annabelle")
	language.Add("weapon_striderbuster", "Strider Buster")
	//THINGS THAT ARE MAP RELATED
	// Half-Life 2
	language.Add("HL2_Chapter1_Title", "POINT INSERTION") 
	language.Add("HL2_Chapter2_Title", "\"A RED LETTER DAY\"") 
	language.Add("HL2_Chapter3_Title", "ROUTE KANAL") 
	language.Add("HL2_Chapter4_Title", "WATER HAZARD") 
	language.Add("HL2_Chapter5_Title", "BLACK MESA EAST") 
	language.Add("HL2_Chapter6_Title", "\"WE DON'T GO TO RAVENHOLM...\"") 
	language.Add("HL2_Chapter7_Title", "HIGHWAY 17") 
	language.Add("HL2_Chapter8_Title", "SANDTRAPS") 
	language.Add("HL2_Chapter9_Title", "NOVA PROSPEKT") 
	language.Add("HL2_Chapter9a_Title", "ENTANGLEMENT") 
	language.Add("HL2_Chapter10_Title", "ANTICITIZEN ONE") 
	language.Add("HL2_Chapter11_Title", "\"FOLLOW FREEMAN!\"") 
	language.Add("HL2_Chapter12_Title", "OUR BENEFACTORS") 
	language.Add("HL2_Chapter13_Title", "DARK ENERGY") 
	language.Add("HL2_Chapter14_Title", "CREDITS") 
	// Half-Life 2: Episode 1
	language.Add("episodic_Chapter1_Title", "Undue Alarm")
	language.Add("episodic_Chapter2_Title", "Direct Intervention")
	language.Add("episodic_Chapter3_Title", "Lowlife")
	language.Add("episodic_Chapter4_Title", "Urban Flight")
	language.Add("episodic_Chapter5_Title", "Exit 17")
	language.Add("episodic_Chapter6_Title", "Coming Soon")
	// Half-Life 2: Episode 2
	language.Add("ep2_Chapter0_Title", "OUR STORY SO FAR...")
	language.Add("ep2_Chapter1_Title", "TO THE WHITE FOREST")
	language.Add("ep2_Chapter2_Title", "THIS VORTAL COIL")
	language.Add("ep2_Chapter3_Title", "FREEMAN PONTIFEX")
	language.Add("ep2_Chapter4_Title", "RIDING SHOTGUN")
	language.Add("ep2_Chapter5_Title", "UNDER THE RADAR")
	language.Add("ep2_Chapter6_Title", "OUR MUTUAL FIEND")
	language.Add("ep2_Chapter7_Title", "T-MINUS ONE")
	language.Add("ep2_Chapter8_Title", "")
	language.Add("ep2_Chapter9_Title", "")
	// Game Over
	language.Add("HL2_GameOver_Object", "ASSIGNMENT: TERMINATED\nSUBJECT: FREEMAN\nREASON: FAILURE TO PRESERVE MISSION-CRITICAL RESOURCES") 
	language.Add("HL2_GameOver_Ally", "ASSIGNMENT: TERMINATED\nSUBJECT: FREEMAN\nREASON: FAILURE TO PRESERVE MISSION-CRITICAL PERSONNEL") 
	language.Add("HL2_GameOver_Timer", "ASSIGNMENT: TERMINATED\nSUBJECT: FREEMAN\nREASON: FAILURE TO PREVENT TIME-CRITICAL SEQUENCE") 
	language.Add("HL2_GameOver_Stuck", "ASSIGNMENT: TERMINATED\nSUBJECT: FREEMAN\nREASON: DEMONSTRATION OF EXCEEDINGLY POOR JUDGMENT") 
	language.Add("Episodic_GameOver_AlyxDead", "THE ALYX VANCE HAS DIED\nWITHOUT HER WE CANNOT PERSEVERE")
	language.Add("EP2_GameOver_AlyxLeft", "THE FREEMAN MUST PROCEED WITH THE ALYX VANCE,\nELSE OUR STRUGGLE IS DOOMED TO FAILURE\nTHOSE WHO DO NOT LEARN FROM THEIR MISTAKES\nARE DOOMED TO AN ENDLESS VORTAL LOOP")
	language.Add("EP2_GameOver_RocketDestroyed", "THE ROCKET HAS BEEN DESTROYED\nMAGNUSSON'S MISGIVINGS ABOUT THE FREEMAN\n ARE COMPLETELY JUSTIFIED.\nTHE GAME NOW ENDS")
	end
	
//Copyright Totsters Extra Stuff - Re-Release of this Addon will result in Castration.